version: "4.15"

services:
  backend:
    build: backend
    ports:
      - 8000:8000
    volumes:
      - ./backend:/profiles

  frontend:
    build: frontend
    ports:
      - 3000:3000
    volumes:
      - ./frontend:/profiles
